#组件的配置文件
spring:
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp
    
    #配置上传的文件大小
    servlet.multipart:
        maxFileSize: 10MB
        
    #数据源的配置
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/oa_j1805?useSSL=false&serverTimezone=UTC
        username: root
        password: root
        
    # JPA配置
    jpa:
        #database-platform: MySQL57
        #showSql: true
        hibernate:
            # 属性的名称为ddlAuto，可以直接使用ddlAuto名称，也可以把字母全改为小写，使用减号隔开
            ddl-auto: update
        properties:
            # Hibernate的方言参考官方的hibernate.cfg.xml文件中的配置
            hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
        # 在一个请求里面打开一个EntityManager，这样可以让实体对象传递给JSP以后，还能够使用懒加载
        # 如果EntityManager被关闭，页面上肯定不能使用懒加载从数据库加载关联数据
        openInView: true

    #自定义错误信息的国际化配置
    message:
        basename: org.fkjava.security.messages
         
        